language: objective-c
osx_image: xcode8
xcode_project: EffectiveSwift.xcodeproj
xcode_scheme: EffectiveSwift
xcode_sdk: iphonesimulator

script:
- xctool -project EffectiveSwift.xcodeproj -scheme 'EffectiveSwift' -configuration Debug -sdk iphonesimulator -arch i386 build
